[Telegram]
# Ensure the bot is invited to your desired Telegram group/channel before using it.
# https://core.telegram.org/bots/tutorial
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHANNEL=@

[CoinMarketCap]
# CoinMarketCap API Key
# https://pro.coinmarketcap.com/account
COINMARKETCAP_API_KEY=

[AiAnalysis]
# OpenRouter API for AI analysis.
# https://openrouter.ai/settings/keys
AI_ENABLED=true
AI_API_KEY=

[Interval]
# Interval for fetching cryptocurrency price data.
# DEFAULT: 3600000 (60 minutes)
UPDATE_INTERVAL_MS=3600000 
# Countdown interval for the console window, showing the time remaining until the next data update. 
# DEFAULT: 60000 (60 seconds)
COUNTDOWN_INTERVAL_MS=60000
